Repository nextcloud/password_policy, pull requests merged in 2021-03, with the labels that each got.

#118 Check all password requirements in one attempt
  lib/PasswordValidator.php
  lib/Validator/LengthValidator.php
  lib/Validator/NumericCharacterValidator.php
Labels: 3. to review, bug

#122 CS fix
  .github/workflows/cs.yml
  .gitignore
  .php_cs.dist
  appinfo/routes.php
  composer.json
  composer.lock
  lib/AppInfo/Application.php
  lib/Capabilities.php
  lib/Compliance/Expiration.php
  lib/Compliance/HistoryCompliance.php
  lib/Compliance/IAuditor.php
  lib/Compliance/IEntryControl.php
  lib/Compliance/IUpdatable.php
  lib/ComplianceService.php
  lib/Controller/APIController.php
  lib/FailedLoginCompliance.php
  lib/Generator.php
  lib/Listener/BeforePasswordUpdatedEventListener.php
  lib/Listener/BeforeUserLoggedInEventListener.php
  lib/Listener/FailedLoginListener.php
  lib/Listener/GenerateSecurePasswordEventListener.php
  lib/Listener/PasswordUpdatedEventListener.php
  lib/Listener/SuccesfullLoginListener.php
  lib/Listener/ValidatePasswordPolicyEventListener.php
  lib/PasswordPolicyConfig.php
  lib/PasswordValidator.php
  lib/Settings.php
  lib/Validator/CommonPasswordsValidator.php
  lib/Validator/HIBPValidator.php
  lib/Validator/IValidator.php
  lib/Validator/LengthValidator.php
  lib/Validator/NumericCharacterValidator.php
  lib/Validator/SpecialCharactersValidator.php
  lib/Validator/UpperCaseLoweCaseValidator.php
  templates/settings-admin.php
  tests/bootstrap.php
  tests/lib/Compliance/HistoryComplianceTest.php
  tests/lib/PasswordPolicyConfigTest.php
  tests/lib/PasswordValidatorTest.php
  tests/lib/Validator/CommonPasswordsValidatorTest.php
  tests/lib/Validator/LengthValidatorTest.php
  tests/lib/Validator/NumericCharacterValidatorTest.php
  tests/lib/Validator/SpecialCharactersValidatorTest.php
  tests/lib/Validator/UpperCaseLowerCaseValidatorTest.php
Labels: 3. to review

#119 Settings in vue
  .eslintrc.js
  .gitignore
  babel.config.js
  css/settings-admin.css
  js/password_policy-settings.js
  js/password_policy-settings.js.map
  js/settings-admin.js
  lib/Settings.php
  package-lock.json
  package.json
  src/AdminSettings.vue
  src/settings.js
  stylelint.config.js
  templates/settings-admin.php
  templates/settings.php
  webpack.js
Labels: 3. to review

#125 Add dependabot config
  .github/dependabot.yml
Labels: 3. to review, enhancement

#136 Migrate to github actions and codecov
  .github/workflows/lint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit.yml
  .travis.yml
  codecov.yml
  composer.json
  js/password_policy-settings.js
  js/password_policy-settings.js.map
  lib/PasswordValidator.php
  tests/phpunit.xml
Labels: 4. to release

#137 Bump dependencies and webpack config
  js/password_policy-settings.js
  js/password_policy-settings.js.map
  package-lock.json
  package.json
Labels: 3. to review, dependencies
