Repository nextcloud/password_policy, pull requests merged in 2022-04, with the labels that each got.

#332 Updating node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#318 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#346 Global configs and npm7
  .github/workflows/block-merge-eol.yml
  .github/workflows/command-compile.yml
  .github/workflows/command-rebase.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/lint.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit.yml
  .php-cs-fixer.dist.php
  babel.config.js
  composer.json
  composer.lock
  js/password_policy-settings.js
  js/password_policy-settings.js.map
  package-lock.json
  package.json
  stylelint.config.js
  tests/lib/Compliance/HistoryComplianceTest.php
  tests/lib/PasswordPolicyConfigTest.php
  tests/lib/PasswordValidatorTest.php
  tests/lib/Validator/CommonPasswordsValidatorTest.php
  tests/lib/Validator/LengthValidatorTest.php
  tests/lib/Validator/NumericCharacterValidatorTest.php
  tests/lib/Validator/SpecialCharactersValidatorTest.php
  tests/lib/Validator/UpperCaseLowerCaseValidatorTest.php
  webpack.config.js
Labels: 3. to review, technical debt, dependencies

#349 Use latest components + accessibility fixes
  js/password_policy-settings.js
  js/password_policy-settings.js.LICENSE.txt
  js/password_policy-settings.js.map
  package-lock.json
  package.json
  src/AdminSettings.vue
Labels: enhancement, 3. to review, dependencies
