Repository nextcloud/password_policy, pull requests merged in 2024-08, with the labels that each got.

#547 chore: update workflows from templates
  .github/workflows/block-merge-eol.yml
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
Labels: 3. to review, dependencies, automated

#642 chore: Update README
  .gitattributes
  .gitignore
  README.md
  REUSE.toml
  screenshots/password_policy_settings.png
  tests/bootstrap.php
  tests/lib/Compliance/HistoryComplianceTest.php
  tests/lib/PasswordPolicyConfigTest.php
  tests/lib/PasswordValidatorTest.php
  tests/lib/Validator/CommonPasswordsValidatorTest.php
  tests/lib/Validator/LengthValidatorTest.php
  tests/lib/Validator/NumericCharacterValidatorTest.php
  tests/lib/Validator/SpecialCharactersValidatorTest.php
  tests/lib/Validator/UpperCaseLowerCaseValidatorTest.php
  tests/phpunit.xml
Labels: 3. to review

#514 fix: Move from private `OC\HintException` to public `OCP\HintException`
  composer.json
  composer.lock
  lib/Compliance/Expiration.php
  lib/Compliance/HistoryCompliance.php
  lib/Compliance/IEntryControl.php
  lib/ComplianceService.php
  lib/Controller/APIController.php
  lib/Generator.php
  lib/PasswordValidator.php
  lib/Validator/CommonPasswordsValidator.php
  lib/Validator/HIBPValidator.php
  lib/Validator/IValidator.php
  lib/Validator/LengthValidator.php
  lib/Validator/NumericCharacterValidator.php
  lib/Validator/SpecialCharactersValidator.php
  lib/Validator/UpperCaseLoweCaseValidator.php
  tests/lib/Compliance/HistoryComplianceTest.php
  tests/lib/Validator/CommonPasswordsValidatorTest.php
  tests/lib/Validator/LengthValidatorTest.php
  tests/lib/Validator/NumericCharacterValidatorTest.php
  tests/lib/Validator/SpecialCharactersValidatorTest.php
  tests/lib/Validator/UpperCaseLowerCaseValidatorTest.php
Labels: bug, 3. to review, technical debt, feedback-requested
