Repository nextcloud/password_policy, pull requests merged in 2024-03, with the labels that each got.

#536 Update npm and node engines versions
  package.json
Labels: dependencies

#516 fix: Migrate some deprecated functions
  lib/ComplianceService.php
  lib/PasswordValidator.php
  lib/Settings.php
  tests/lib/PasswordValidatorTest.php
Labels: bug, 3. to review, feedback-requested

#512 chore: Update workflows from organization
  .github/workflows/command-compile.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node-when-unrelated.yml
  .github/workflows/node.yml
  .github/workflows/pr-feedback.yml
Labels: 3. to review, dependencies, feedback-requested
