Repository nextcloud/password_policy, pull requests merged in 2024-09, with the labels that each got.

#643 chore: update workflows from templates
  .github/workflows/command-compile.yml
  .github/workflows/command-rebase.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/reuse.yml
Labels: 3. to review, dependencies, automated

#652 chore: Fix REUSE license extraction
  AUTHORS.md
  LICENSES/GPL-3.0-or-later.txt
  LICENSES/MPL-2.0.txt
  REUSE.toml
  css/settings-BpwckKO3.chunk.css
  css/settings-Cw0VUq14.chunk.css
  js/password_policy-settings.mjs
  js/password_policy-settings.mjs.license
  js/password_policy-settings.mjs.map
  js/password_policy-settings.mjs.map.license
  js/vendor.LICENSE.txt
  package.json
  vite.config.js
Labels: 3. to review

#649 chore: Update PHPUnit tests
  .github/workflows/phpunit-sqlite.yml
  .gitignore
  composer.json
  composer.lock
  tests/lib/Compliance/HistoryComplianceTest.php
  tests/lib/PasswordPolicyConfigTest.php
  tests/lib/Validator/CommonPasswordsValidatorTest.php
  tests/lib/Validator/LengthValidatorTest.php
  tests/lib/Validator/NumericCharacterValidatorTest.php
  tests/lib/Validator/SpecialCharactersValidatorTest.php
  tests/lib/Validator/UpperCaseLowerCaseValidatorTest.php
  tests/phpunit.xml
  vendor-bin/phpunit/composer.json
  vendor-bin/phpunit/composer.lock
Labels: 3. to review, technical debt

#650 chore: Migrate deprecated app config access to `IAppConfig`
  lib/AppInfo/Application.php
  lib/PasswordPolicyConfig.php
  tests/lib/PasswordPolicyConfigTest.php
Labels: 3. to review, ♻️ refactor

#651 chore: Add psalm
  .github/workflows/psalm.yml
  LICENSES/AGPL-3.0-only.txt
  REUSE.toml
  composer.json
  lib/Capabilities.php
  lib/Compliance/Expiration.php
  lib/Compliance/HistoryCompliance.php
  lib/ComplianceService.php
  lib/FailedLoginCompliance.php
  lib/Generator.php
  lib/Listener/BeforePasswordUpdatedEventListener.php
  lib/Listener/BeforeUserLoggedInEventListener.php
  lib/Listener/FailedLoginListener.php
  lib/Listener/GenerateSecurePasswordEventListener.php
  lib/Listener/PasswordUpdatedEventListener.php
  lib/Listener/SuccesfullLoginListener.php
  lib/Listener/ValidatePasswordPolicyEventListener.php
  lib/PasswordPolicyConfig.php
  lib/Validator/CommonPasswordsValidator.php
  lib/Validator/HIBPValidator.php
  psalm.xml
  tests/psalm-baseline.xml
  tests/stubs/OC_User_LoginException.php
  vendor-bin/psalm/composer.json
  vendor-bin/psalm/composer.lock
Labels: 3. to review, technical debt
