Repository nextcloud/password_policy, pull requests merged in 2025-01, with the labels that each got.

#697 [master] Fix npm audit
  css/password_policy-settings.css
  css/settings-Bm9V54dt.chunk.css
  js/password_policy-settings.mjs
  js/password_policy-settings.mjs.license
  js/password_policy-settings.mjs.map
  js/password_policy-settings.mjs.map.license
  package-lock.json
Labels: 3. to review, dependencies

#676 [stable29] Fix npm audit
  css/password_policy-settings.css
  css/settings-DN3tHgGk.chunk.css
  js/password_policy-settings.mjs
  js/password_policy-settings.mjs.map
  js/vendor.LICENSE.txt
  package-lock.json
Labels: 3. to review, dependencies

#675 [stable30] Fix npm audit
  LICENSES/GPL-3.0-or-later.txt
  LICENSES/MPL-2.0.txt
  REUSE.toml
  css/password_policy-settings.css
  css/settings-BjPOARRj.chunk.css
  js/password_policy-settings.mjs
  js/password_policy-settings.mjs.license
  js/password_policy-settings.mjs.map
  js/vendor.LICENSE.txt
  package-lock.json
  package.json
  vite.config.js
Labels: 3. to review, dependencies

#718 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#717 feat: Allow to configure different policies per password context
  .eslintrc.json
  REUSE.toml
  appinfo/info.xml
  css/password_policy-settings.css
  css/settings-Bm9V54dt.chunk.css
  css/settings-BpwckKO3.chunk.css
  css/settings-JzBOrW1D.chunk.css
  css/settings-rj0ps52C.chunk.css
  js/password_policy-settings.mjs
  js/password_policy-settings.mjs.license
  js/password_policy-settings.mjs.map
  js/password_policy-settings.mjs.map.license
  lib/Capabilities.php
  lib/Generator.php
  lib/Listener/GenerateSecurePasswordEventListener.php
  lib/Listener/ValidatePasswordPolicyEventListener.php
  lib/PasswordPolicyConfig.php
  lib/PasswordValidator.php
  lib/Settings/Settings.php
  lib/Validator/CommonPasswordsValidator.php
  lib/Validator/HIBPValidator.php
  lib/Validator/IValidator.php
  lib/Validator/LengthValidator.php
  lib/Validator/NumericCharacterValidator.php
  lib/Validator/SpecialCharactersValidator.php
  lib/Validator/UpperCaseLoweCaseValidator.php
  openapi.json
  package-lock.json
  package.json
  src/AdminSettings.vue
  src/capabilities.d.ts
  src/components/AddPolicyButton.vue
  src/components/ComplianceConfig.vue
  src/components/PasswordPolicy.vue
  src/constants.ts
  src/settings.ts
  src/types.d.ts
  tests/lib/PasswordPolicyConfigTest.php
  tests/lib/PasswordValidatorTest.php
  tests/lib/Validator/CommonPasswordsValidatorTest.php
  tests/lib/Validator/HIBPValidatorTest.php
  tests/lib/Validator/LengthValidatorTest.php
  tests/lib/Validator/NumericCharacterValidatorTest.php
  tests/lib/Validator/SpecialCharactersValidatorTest.php
  tests/lib/Validator/UpperCaseLowerCaseValidatorTest.php
  tsconfig.json
  vite.config.ts
Labels: enhancement, 3. to review, 🍀 2025-Spring

#726 chore(CI): Updating npm-audit-fix.yml workflow from template
  .github/workflows/npm-audit-fix.yml
Labels: dependencies
